classDiagram
    class Profesor {
       -idProfesor : int
       -nombre : string
       -apellido : string
       -email : string
       -departamento : string
       +crearGrupo() : void
       +calificarEstudiante(estudianteId : int, nota : float) : void
    }

    class Estudiante {
        -idEstudiante: int
        -nombre: string
        -apellido : string
        -email: string
        -carrera: string
        +registrar(): void
        +editarPerfil(): void
        +consultarCursosDisponibles(): List<Curso>
        +consultarCursosMatriculados(): List<Curso>
    }
 
    class Curso {
        -codigo: string
        -nombre: string
        -creditos: int
        +matricular(): void
        +retirar(): void
    }

    class Periodo {
        -anio: int
        -nombre: string
        -activo: boolean
        +iniciarPeriodo(): void
        +finalizarPeriodo(): void
    }

    class PeriodoCurso {
        -idCurso: string
        -idPeriodo: int
        -idProfesor: int 
        -horario: string
        +asingnarProfesor(): void
        +definirHorario(): void
    }

    class Grupo {
      -idGrupo : int
      -codigo : string
      -capacidad : int
      -aula : string
      -horario : string
      -estado : string
      +asignarProfesor(profesorId : int) : void
      +verificarCupo() : bool
    }

    class Inscripcion {
      -idInscripcion : int
      -fechaInscripcion : date
      -estado : string  <<ej: "Matriculado","Retirado">>
      -notaFinal : float
      -letra : string
      +matricular() : void
      +retirar() : void
    }
    %% Relaciones simplificadas con cardinalidades

    %%Curso "1" --> "*" Grupo : tiene
    %%Periodo "1" --> "*" Grupo : contiene
    %%Profesor "1" --> "0..*" Grupo : imparte
    %%Profesor "0..*" --> "0..*" Curso : puede_impartir
    %%Estudiante "1" --> "0..*" Inscripcion : realiza
    %%Grupo "1" --> "0..*" Inscripcion : recibe
    %%Inscripcion "*" --> "1" Estudiante
    %%Inscripcion "*" --> "1" Grupo
   

    %%Estudiante "1" --> "*" PeriodoCurso: matriculado en
    %%Curso "1" --> "*" Periodo : ofrecido en
    %%Periodo "1" --> PeriodoCurso : contiene
