classDiagram
    class Estudiante {
        -id: int
        -nombre: string
        -email: string
        -carrera: string
        +registrar(): void
        +editarPerfil(): void
        +consultarCursosDisponibles(): List<Curso>
        +consultarCursosMatriculados(): List<Curso>
    }
 
    class Curso {
        -codigo: string
        -nombre: string
        -creditos: int
        +matricular(): void
        +retirar(): void
    }

    class Periodo {
        -anio: int
        -nombre: string
        -activo: boolean
        +iniciarPeriodo(): void
        +finalizarPeriodo(): void
    }

    class PeriodoCurso {
        -idCurso: string
        -idPeriodo: int
        -idProfesor: int 
        -horario: string
        +asingnarProfesor(): void
        +definirHorario(): void

    }
 
    Estudiante "1" --> "*" PeriodoCurso: matriculado en
    Curso "1" --> "*" Periodo : ofrecido en
    Periodo "1" --> PeriodoCurso : contiene
